import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "@/components/Menu/menu";
import Footer from "@/components/Footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Balmain Inc.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
          <Menu />
          {children}
          <Footer />
      </body> 
    </html>
  );
}
